# from django.conf.urls import url
from . import views
from django.urls import path, re_path
urlpatterns = [
    # url(r'^$', views.home, name='home'),
    # url(r'^(?P<book_id>[0-9]+)$' , views.displayBook, name='displayBook'),
    # url(r'^(?P<book_id>[0-9]+)/read/$' , views.readBook, name='readBook'),
    # url(r'^(?P<book_id>[0-9]+)/addfavourite/$' , views.addfavourite, name='addfavourite'),
    # url(r'^favourites/$', views.favourites, name='favourites'),
    # url(r'^highrated/$', views.highrated, name='highrated'),
    # url(r'^trending/$', views.trending, name='trending'),
    # url(r'^editorchoice/$', views.editorchoice, name='editorchoice'),
    # url(r'^search/$', views.search, name='search'),
    # url(r'^horror/$', views.horror, name='horror'),
    # url(r'^Thriller/$', views.Thriller, name='Thriller'),
    # url(r'^Romantic/$', views.Romantic, name='Romantic'),
    # url(r'^Mystery/$', views.Mystery, name='Mystery'),
    # url(r'^Fiction/$', views.Fiction, name='Fiction'),
    # url(r'^Spiritual/$', views.Spiritual, name='Spiritual'),
    # url(r'^Psychology/$', views.Psychology, name='Psychology'),
    # url(r'^upload/$', views.upload, name='upload'),
    # url(r'^useruploads/$', views.useruploads, name='useruploads'),




    re_path(r'^$', views.home, name='home'),
    re_path(r'^(?P<book_id>[0-9]+)$' , views.displayBook, name='displayBook'),
    re_path(r'^(?P<book_id>[0-9]+)/read/$' , views.readBook, name='readBook'),
    re_path(r'^(?P<book_id>[0-9]+)/addfavourite/$' , views.addfavourite, name='addfavourite'),
    re_path(r'^favourites/$', views.favourites, name='favourites'),
    re_path(r'^highrated/$', views.highrated, name='highrated'),
    re_path(r'^trending/$', views.trending, name='trending'),
    re_path(r'^editorchoice/$', views.editorchoice, name='editorchoice'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^horror/$', views.horror, name='horror'),
    re_path(r'^Thriller/$', views.Thriller, name='Thriller'),
    re_path(r'^Romantic/$', views.Romantic, name='Romantic'),
    re_path(r'^Mystery/$', views.Mystery, name='Mystery'),
    re_path(r'^Fiction/$', views.Fiction, name='Fiction'),
    re_path(r'^Spiritual/$', views.Spiritual, name='Spiritual'),
    re_path(r'^Psychology/$', views.Psychology, name='Psychology'),
    re_path(r'^upload/$', views.upload, name='upload'),
    re_path(r'^useruploads/$', views.useruploads, name='useruploads'),


    # path('^$/', views.home, name='home'),
    # path('^(?P<book_id>[0-9]+)$' , views.displayBook, name='displayBook'),
    # path('^(?P<book_id>[0-9]+)/read/$' , views.readBook, name='readBook'),
    # path('^(?P<book_id>[0-9]+)/addfavourite/$' , views.addfavourite, name='addfavourite'),
    # path(r'favourites/$', views.favourites, name='favourites'),
    # path('^highrated/$', views.highrated, name='highrated'),
    # path('^trending/$', views.trending, name='trending'),
    # path('^editorchoice/$', views.editorchoice, name='editorchoice'),
    # path('^search/$', views.search, name='search'),
    # path('^horror/$', views.horror, name='horror'),
    # path('^Thriller/$', views.Thriller, name='Thriller'),
    # path('^Romantic/$', views.Romantic, name='Romantic'),
    # path('^Mystery/$', views.Mystery, name='Mystery'),
    # path('^Fiction/$', views.Fiction, name='Fiction'),
    # path('^Spiritual/$', views.Spiritual, name='Spiritual'),
    # path('^Psychology/$', views.Psychology, name='Psychology'),
    # path('^upload/$', views.upload, name='upload'),
    # path('^useruploads/$', views.useruploads, name='useruploads'),
    ]